import type { FlagDoc, TopicDoc } from "../types.js";

const flags: FlagDoc[] = [
  { name: "workspace", short: "w", type: "string", description: "Workspace ID; defaults to the selected official CLI profile" },
  { name: "branch", short: "b", type: "string", description: "Branch label; use the same branch for publishing and evaluating" },
  { name: "profile", short: "p", type: "string", description: "Official CLI profile name" },
  { name: "output", short: "o", type: "string", default: "summary", description: "summary or json" },
  { name: "verbose", short: "v", type: "boolean", default: "false", description: "Print the request the CLI makes and the raw platform response beside the normal output; useful when a refusal or a finding needs to be traced to the route that produced it" },
];
const messageFlag: FlagDoc = { name: "message", short: "m", type: "string", description: "Short label for the Version History entry this publish creates; ignored when the definition is unchanged" };
const sourceFlags: FlagDoc[] = [
  { name: "file", short: "f", type: "string", description: "Path to one policy XanoScript document; use this or --stdin. policy parse also accepts the path as a positional argument" },
  { name: "stdin", type: "boolean", description: "Read one policy document from standard input" },
];

export const policyDoc: TopicDoc = {
  topic: "policy",
  title: "Xano CLI - Workspace Policies",
  description: `Policy support in the official @xano/cli uses the existing profile and Metadata API client. Requires policy-enabled builds of the CLI and instance. A policy combines its human description with deterministic check rules and lives as workspace XanoScript. The policy language - syntax, fields, rules, refusal messages and versioning - is documented once, in xano_xanoscript_docs({topic: "policies"}) (mode: "quick_reference" for the short form; the full topic carries every check's description); this topic covers the commands.

Use the authenticated Xano MCP tools for live tool calls, or these CLI commands for local workspace files. The standalone developer MCP serves this documentation; it does not itself authenticate to your workspace.`,
  ai_hints: `Discover exact check parameters with policy catalogue; each entry carries a human label beside its check id. Native policy parse is the validation authority. The developer MCP's language server checks policy syntax locally, and checks rules only as warnings against its bundled copy of the catalogue, which may be older than the instance. An unknown check id is refused by parse, publish and workspace push with payload.code policy_unknown_check, naming the nearest ids, and the CLI adds a pointer to xano policy catalogue. Do not invent a local policy parser. policy parse prints canonical source, which is sparse and orders params the catalogue's way, so do not read a shorter file as a lost setting.

Reads, parsing and evaluation need the workspace:policy permission at read level; creating, updating and deleting need it at create, update or delete level. A refused request prints the platform's message and what to do about it, keyed on the refusal's code: the feature is off, the role lacks the permission (an instance admin grants it; a new token does not help), or the token was created without the scope (create one that has it). workspace push lets unchanged policy files through for any reader; a changed policy file from a caller whose permission does not allow the change refuses the whole push, so exclude them with -e "policies/*" or pull again.

Policy source uses active = true or active = false before enforcement. The retired lifecycle field is refused. policy list labels rows Active, Mandatory; Active, Advisory; or Inactive. Inactive policies are saved directly, skipped by branch checks, and reported with status inactive.

A parse or validation error in summary output is located at line N, col M, with line 1 the first line, followed by the offending text; -o json keeps the platform payload untouched, whose line and col count from 1 too. Every policy command run with -o json reports its own failure as one object on stdout rather than as prose on stderr: {"error": {"message": "...", "exit": 1}}, and exits 1. Exit 2 is never an error object: it is reserved for blocking findings, which are ordinary results.

policy evaluate and workspace push print the platform's policy_check verdict (see the Metadata API policy topic for the statuses). Their exit code follows the import and the blocking policies only: 1 when the import or the request fails, 2 whenever policy_check.blocking is true (an active mandatory policy has findings; an inactive policy never blocks), and 0 otherwise. A pass, a fail and not_applicable (no active policy on the branch) print a headline with the platform's message; disabled, forbidden, unavailable, error or no feedback at all print one warning line on stderr with the platform's status and message, and leave the exit code alone. For CI, key on policy_check.blocking in -o json rather than on status: advisory findings arrive as status fail with blocking false. A policy finding never rolls back imported code on a branch that is not live. A push to the live branch is gated before it commits: a 403 policy_gate refusal exits 2, says nothing was imported, lists the blocking findings and introduced/changed counts, and under -o json prints {imported: false, refused: <payload>}; --policy-override "<reason>" sends an audited override (workspace:policy update), and --no-transaction to live is refused (exit 1). A create past the plan's per-branch cap is refused with policy_plan_limit, naming the plan. Releases carry policies: release create, push and import print the release's stored policy check; tenant deploy_release --check prints the deploy gate's verdict and --override-reason overrides it; tenant_deploy_request set_status and bypass take --override-policy; a refused deploy exits 2. release deploy --set_live and branch set_live exit 2 when the set-live gate refuses (a refused release deploy keeps the new branch and names it), and function create and function edit exit 2 when the live-branch publish gate refuses the save (nothing is saved); each takes --policy-override "<reason>" (workspace:policy update; only with the user's own reason), a blank one is refused before any request, and any other failure exits 1. A workspace push (its --dry-run too), branch set_live, release deploy --set_live or policy delete (of an active mandatory policy) that weakens a mandatory policy without workspace:policy update is refused with policy_weakening_permission_required and exits 1, a permission refusal rather than a blocking finding: the CLI prints the platform's sentence and how to go on (leave the policy files out with -e "policies/*"; a deployed release's branch stays and is named), and --policy-override does not lift it. policy parse and policy publish print rule warnings on stderr.

A rule with zero objects checked and no findings has status no_objects and message no objects checked. Older stored runs keep pass with checked: 0; readers accept both. The run and policy_check stay pass when nothing failed, and policy_check.message names the unchecked rules. Merge, publish and deploy gates read findings and are unaffected. The CLI summary renders both as no objects checked, never as an error; policy status keeps its no_objects_checked row status.

A run can hold tens of thousands of findings, so large ones are read a page at a time. The policy_check a workspace push answers lists the first 100 findings and blocking findings, beside counts {findings, blocking, errors}, total and truncated; when the lists were cut the push prints the counts, heads each list "first 100 of N" and ends with Listed: the first 100 of N; \`xano policy runs <run_id>\` has them all. policy runs <id> reads a run's summary and one page of its findings (--offset, --limit up to 500, and filters), or every page with --all, and policy status reads the latest run's summary; policy evaluate --summary answers the run summary with its first 50 findings; policy evaluate without it still answers the whole run.

Publishing an identical definition writes nothing and prints No changes; JSON output carries unchanged: true. Do not add a cosmetic edit to force a version. Version history is listed, diffed and restored in the Xano dashboard only; there is no CLI command for it. policy status reads the platform's latest_run for each policy: a policy is stale when it changed after the branch's newest run, so that run's findings no longer describe it.

workspace pull writes policies to policies/<KEY>.xs when the credential can read them (without workspace:policy read the pull succeeds and omits them) and prints one hint after a pull that included them: Run \`xano skills pull\` to install the policies skill for your coding agent (see the skills topic). workspace push includes policies in the normal multidoc import and reports policy_check afterward; the workspace topic covers its -m/--message. sandbox push and ephemeral push (and their --dry-run) and release push carry policy files while the instance's Policies feature is on: a sandbox or ephemeral push lands them without evaluating them (no policy_check), and release push sends policies/*.xs with the rest and prints the release's stored policy check. A release built by release push carries those files only for a caller holding workspace:policy create and update; for anyone else it carries the workspace's live-branch policies instead, and the push prints the platform's policies_skipped message naming the files when they differ from the live ones. release import of an archive that carries policies needs the same workspace:policy create and update: without them the platform refuses it, nothing is stored, and the CLI prints the platform's message and the remedy for the role or the token. A push to a remote tenant, a push to a tenant created before policies (it has no policy table until its next platform update), or any push while the feature is off leaves them out, and the push prints the platform's policies_skipped message once, as a warning naming the files and why. While the instance's Policies feature is off, workspace pull carries no policies (and prints no skills hint) and workspace push leaves its policy files out, printing the platform's one line instead of a policy count. Existing workspace push deletion/sync behavior remains governed by its normal flags.`,
  related_topics: ["workspace", "profile", "branch", "skills"],
  commands: [
    { name: "policy catalogue", description: "List built-in checks, their schemas and analysis limitations from the instance. The full catalogue is long; --check narrows it to one check id in either output mode, and an unknown id names the closest matches.", usage: "xano policy catalogue [options]", flags: [...flags, { name: "check", type: "string", description: "Show only this check id" }], examples: ["xano policy catalogue -o json", "xano policy catalogue --check object.auth_required"] },
    { name: "policy list", description: "List policies on the selected branch, each with its active state, id and current version.", usage: "xano policy list [options]", flags, examples: ["xano policy list -b dev -o json"] },
    {
      name: "policy create",
      description: "Create an independent Active, Advisory policy from a platform goal (the goals in policy catalogue -o json). Copies the goal's sparse settings; every needs path must be filled with --param. Parsed natively before saving. A taken goal key gets a free numeric suffix (case-insensitive); a taken explicit --key is refused. Never updates an existing policy and stores no link to the goal. Rule warnings go to stderr; -o json prints the saved policy.",
      usage: "xano policy create --goal <id> [--key KEY] [--param N.path=JSON ...] [options]",
      flags: [...flags, messageFlag, { name: "goal", type: "string", required: true, description: "Goal id from the catalogue's goals" }, { name: "key", type: "string", description: "Policy key; defaults to the goal's suggested key" }, { name: "param", type: "string", description: "Repeatable N.path=JSON override; rule numbers start at 1, and the N. prefix is optional for a single-rule goal" }],
      examples: ["xano policy create --goal endpoints_need_login -b dev", "xano policy create --goal no_pii_in_responses --key DATA-020 --param 'fields=[\"email\",\"ssn\"]'"],
    },
    {
      name: "policy parse",
      description: "Parse and format source on the instance without saving. Summary output is canonical XanoScript; JSON includes {policy, source}. The file may be given as a positional argument or with --file - they are the same input, and --stdin is unchanged.",
      usage: "xano policy parse [file] [options]",
      args: [{ name: "file", required: false, description: "Path to one policy XanoScript document, the positional form of --file. Omit it and pass --stdin to read the document from standard input" }],
      flags: [...flags, ...sourceFlags],
      examples: ["xano policy parse policies/AUTH-EXAMPLE.xs", "xano policy parse --file policies/AUTH-EXAMPLE.xs", "cat policies/AUTH-EXAMPLE.xs | xano policy parse --stdin -o json"],
    },
    { name: "policy publish", description: "Parse one policy, then create or update by its stable key on the selected branch using canonical source. Prints Published KEY (Version N), or No changes to KEY (Version N) when the definition already matches what is stored. Use workspace push for an atomic multi-policy import.", usage: "xano policy publish --file <path> [options]", flags: [...flags, ...sourceFlags, messageFlag], examples: ["xano policy publish --file policies/AUTH-EXAMPLE.xs -b dev", "xano policy publish --file policies/AUTH-EXAMPLE.xs -m \"Tightened the scope\""] },
    { name: "policy evaluate", description: "Evaluate active policies and store a new run, then print the platform's verdict and the run's findings. Exits 2 when policy_check.blocking is true, and 0 for every other verdict; not_applicable (no active policy) prints a headline with the platform's message and is no run: nothing is stored, so there is no Not stored line and nothing new in policy runs. Only a disabled, forbidden, unavailable or errored verdict prints one warning line. A credential that may read but not write gets its findings with nothing stored, and the CLI says Not stored. --policy KEY tries that one policy alone, even if inactive: nothing is stored or audited, the latest run is untouched, nothing is gated, and each rule's clear objects are named; an inactive trial never exits 2, and a blank key is refused before any request.", usage: "xano policy evaluate [options]", flags: [...flags, { name: "policy", type: "string", description: "Try this one policy key alone (a trial: never stored or audited)" }, { name: "run-detail", type: "boolean", default: "false", description: "Also print what this run recorded: each policy's statement and each rule's name and resolved settings" }, { name: "summary", type: "boolean", default: "false", description: "Send answer: summary: answer the run summary (counts, each policy's verdict, rule results) and its first 50 findings instead of the whole run, and say which run has the rest. -o json passes that answer through" }], examples: ["xano policy evaluate -b dev -o json", "xano policy evaluate --run-detail", "xano policy evaluate --summary -o json", "xano policy evaluate --policy AUTH-001"] },
    {
      name: "policy runs",
      description: "List the runs the branch retains (only the newest twenty exist), newest first, with status, finding count, objects checked, trigger and start time. With a run id, read that one run, including one older than the latest, which policy status cannot reach: its summary (counts, each policy's verdict, rule results) and one page of its findings in the platform's order, blocking first, 100 unless --limit says otherwise; a page that is not every finding is marked (one page) and names the next page's --offset. --all reads every page instead (500 a request, saying so on stderr when there are more) and prints or returns every matching finding. The filter flags narrow the findings on the instance; a repeated flag matches any of its values. JSON output is the platform's own body: the run summaries for a list, and for one id the run summary with findings, the page's findings as an array (every one with --all), and findings_page {total, offset, limit, next_offset}, next_offset null after the last. The finding flags need a run id. --release <name> reads a release's policy check (stored when it was cut) the same way, plus its shipped policies; --release-id <id> reads it by id (exclusive with --release and --branch); --recheck checks the release again from its archive and stores the run. Needs the workspace:policy permission at read level.",
      usage: "xano policy runs [run_id] [options]",
      flags: [
        ...flags,
        { name: "release", type: "string", description: "Read this release's policy check instead of a branch run" },
        { name: "release-id", type: "number", description: "Read a release's policy check by release id" },
        { name: "recheck", type: "boolean", default: "false", description: "With --release or --release-id, check the release again and store the run" },
        { name: "limit", type: "number", description: "Without a run id, the newest N runs (1-20, default 20); with one, how many findings to print (1-500, default 100)" },
        { name: "offset", type: "number", default: "0", description: "With a run id, how many findings to skip" },
        { name: "all", type: "boolean", default: "false", description: "With a run id, read every page and print or return every matching finding; not with --offset or --limit" },
        { name: "blocking", type: "boolean", default: "false", description: "With a run id, only the blocking findings" },
        { name: "advisory", type: "boolean", default: "false", description: "With a run id, only the advisory findings" },
        { name: "policy", type: "string", description: "With a run id, only this policy key's findings; repeatable" },
        { name: "rule", type: "string", description: "With a run id, only this rule id's findings (AUTH-001.R1); repeatable" },
        { name: "severity", type: "string", description: "With a run id, only findings of this severity (critical, high, medium, low); repeatable" },
        { name: "kind", type: "string", description: "With a run id, only findings on this object kind; repeatable" },
        { name: "object", type: "string", description: "With a run id, only findings on this object, written type:id (query:18); repeatable" },
        { name: "tag", type: "string", description: "With a run id, only findings whose policy or object carries this tag; repeatable" },
        { name: "search", type: "string", description: "With a run id, only findings whose policy key or title, rule title, object name or message contains this text" },
        { name: "run-detail", type: "boolean", default: "false", description: "With a run id, also print the policy statements and rule settings that run recorded" },
      ],
      examples: ["xano policy runs", "xano policy runs --limit 5", "xano policy runs 1674 --run-detail -o json", "xano policy runs 1674 --offset 100 --limit 100", "xano policy runs 1674 --all -o json", "xano policy runs 1674 --blocking --policy AUTH-001 --severity critical", "xano policy runs --release v1.2", "xano policy runs --release-id 12 --recheck"],
    },
    { name: "policy delete", description: "Delete a policy from the selected branch, by policy key or by id; its Version History is kept. An unresolved name is refused naming the policies the branch does have. Prompts before deleting; --force skips the prompt. The delete sends the updated_at it listed, so a policy changed after that (for example while the prompt waited) is refused with policy_stale and nothing is deleted: run the command again. This is the only way to remove a policy from the CLI: workspace push is additive, so deleting policies/KEY.xs and pushing leaves the policy in place. Needs the workspace:policy permission at delete level.", usage: "xano policy delete <key-or-id> [options]", flags: [...flags, { name: "force", short: "f", type: "boolean", default: "false", description: "Skip the confirmation prompt; only with the user's explicit confirmation" }], examples: ["xano policy delete TMP-DX-001", "xano policy delete 922 --force -o json"] },
    {
      name: "policy status",
      description: "Inspect stored policy/run state without evaluating. The Enforcement column reads Mandatory or Advisory, and a finding count reads (blocking) when the latest run judged it blocking: the run evaluated the policy in its current version as active and mandatory. A policy is stale when it changed after the branch's newest run (the platform's latest_run), so that run's findings no longer describe it. Informational (exit 0) by default; with --fail-on-findings it exits 2 when the latest run has blocking findings, else 1 for stale, missing or errored evaluation evidence (advisory findings still exit 0), and a nonzero exit is always explained by one line naming the reason. A blocking reason is a prediction: the merge gate evaluates the branch again before a merge. In -o json each row's status is one of pass, fail, error, stale, not_evaluated, no_checks, no_objects_checked or inactive, with blocking, rules_unchecked (a pass whose rules checked no objects) and counted (whether its findings come from the latest run's evidence); --fail-on-findings adds fail_on_findings: {exit, reason}. It reads the latest run's summary, not the whole run, so in -o json run carries each policy's finding count and verdict rather than the findings; xano policy runs <id> lists them.",
      usage: "xano policy status [options]",
      flags: [...flags, { name: "fail-on-findings", type: "boolean", default: "false", description: "Exit 2 when the latest run has blocking findings; otherwise exit 1 for stale, missing or errored evaluation evidence" }, { name: "run-detail", type: "boolean", default: "false", description: "Also print what the latest run recorded: each policy's statement and each rule's name and resolved settings. Summary output only" }],
      examples: ["xano policy status -b dev -o json", "xano policy status --fail-on-findings -o json", "xano policy status --run-detail"],
    },
  ],
};
